AdminAlmacen/ViewModels/ProductosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminAlmacen.ViewModels
{
    public class ProductosViewModel
    {
        public Guid id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal costo { get; set; }
    }
}

AdminAlmacen/Controllers/ProductosController.cs
using AdminAlmacen.Models;
using AdminAlmacen.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminAlmacen.Controllers
{
    [Authorize]
    public class ProductosController : Controller
    {
        // GET: Productos
        public ActionResult Index()
        {
            /*List<ProductosViewModel> productos;
            using (AlmacenEntities db = new AlmacenEntities())
            {
                productos = (from prod in db.productos select new ProductosViewModel
                             {
                                 id = prod.id,
                                 codigo = prod.codigo,
                                 nombre = prod.nombre,
                                 descripcion = prod.descripcion,
                                 costo = prod.costo
                             }).ToList();
            }
            return View(productos);*/
            return View();
        }

        public ActionResult Editar(Guid id)
        {
            
            /*List<ProductosViewModel> productos;
            using (AlmacenEntities db = new AlmacenEntities())
            {
                var prodq = db.productos.Find(id);
                productos = (from prod in db.productos
                             select new ProductosViewModel
                             {
                                 id = prod.id,
                                 codigo = prod.codigo,
                                 nombre = prod.nombre,
                                 descripcion = prod.descripcion,
                                 costo = prod.costo
                             }).ToList();
            }*/
            //return View(productos);
            return View();
        }
    }
}

AdminAlmacen/Views/Productos/Index.cshtml
@model List<AdminAlmacen.ViewModels.ProductosViewModel>
@{
    ViewBag.Title = "IndexProductos";
}
@section css{
    @Styles.Render("~/Content/Tablescss")
}
<div class="row">
    <a class="btn btn-success" href="~/Productos/Nuevo">Nuevo</a>
</div>
<br />
<br />
<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-dark">
                    <tr>
                        <th>Código</th>
                        <th>Producto</th>
                        <th>Descripción</th>
                        <th>Costo</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var pro in Model)
                    {
                        <tr>
                            <td>@pro.codigo</td>
                            <td>@pro.nombre</td>
                            <td>@pro.descripcion</td>
                            <td>$@pro.costo</td>
                            <td>
                                <a class="btn btn-primary" href="~/Productos/Editar/@pro.id">Editar</a>
                                <a class="btn btn-primary" href="@Url.Action("Editar","Productos", new { id = pro.id })">Editar2</a>
                                <a class="btn btn-danger" href="~/Productos/Eliminar/@pro.id">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">

</div>
@section js{
    @Scripts.Render("~/Content/Tablesjs")
}